### ISSUE TITLE
ssGSEA behavior

### ISSUE THREAD

**Issue by redst4r** [Gibbsdavidl/gssnng#20]
Looks like the `ssgsea()` function in gssnng is doing something "wrong". At least as far as the classical GSEA is defined.
Here's how it calculates (part of) this running sum
```python
#determining denominator value
i = 1 #current rank stepping through listing of sorted genes
for gene in keys_sorted:
    if gene in gene_set:
        P_GW_denominator += i ** omega
    i += 1
```
Note how it increments by **powers of the rank** (i). Ususally GSEA does this differently (I had to read several papers, they're pretty bad at explaining it, [this](https://www.pathwaycommons.org/guide/primers/data_analysis/gsea/) is a good source): 
- There's a thing called the `rank order statistic` (i.e. the thing that gets ranked). Could be the expression of each gene, or the foldchange in a DEG analysis.
- It is the **absolute value of the rank statistic** that is used as an increment.

Currently it almost does the **opposite** of what's expected:
- The highest ranking gene (the one with the higest expression) gets rank 1 and causes a small increment to the score
- The 2nd-highest increments the score, but by 2: It actually has more influence than the top gene
- the middle-rank genes will actually increment the score by far more then the top rank genes!
- The gene on the bottom of the list increments the score *the most*, since its rank==#genes

Hence:
```python
#determining denominator value
i = 1 #current rank stepping through listing of sorted genes
for gene in keys_sorted:
    if gene in gene_set:
        P_GW_denominator += np.abs(xsorted[gene]) ** omega
    i += 1
```
I'll add a pull request for this in a bit

**Comment by Gibbsdavidl** [comment]
Thanks for getting that fix in!
